WEAVE_AND_THE_WHEEL_PROFILES = 'WeaveAndTheWheelProfiles'
REQUEST = 'request'
USER_ATTRIBUTES = 'userAttributes'
EMAIL = 'email'
PREFERRED_USERNAME = 'preferred_username'
SUB = 'sub'
SHARED_CONTENT = 'shared_content'
CREATION_DATE = 'creation_date'
PROFILE_PIC = 'profile_pic'

DYNAMODB = 'dynamodb'
PARTION_KEY = 'PartitionKey'
