FROM public.ecr.aws/lambda/python:3.11-x86_64

# Install System dependencies
RUN yum update -y && yum install -y \
    curl \
    python3 \
    python3-pip \
    && yum clean all

# Configure Poetry
ENV POETRY_VERSION=1.5.1 \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR='/var/cache/pypoetry' \
    POETRY_HOME='/usr/local'

# Install Poetry
RUN pip3 install --upgrade pip
RUN pip3 install poetry==${POETRY_VERSION}

# Copy dependency files first for better caching
COPY poetry.lock pyproject.toml ./

# Set working directory
WORKDIR /var/task

# Install dependencies
RUN poetry install --no-root

# Copy only the src code
COPY src/ ./src/

# Run the app
CMD ["src.fetch_profile.lambda_handler"]